// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZCtlmIamTGlZkWU_vuoBEePyqKhMOHM',
    appId: '1:336645454105:web:943e4faf3f4e9d08b3ed88',
    messagingSenderId: '336645454105',
    projectId: 'weblearn-9f82a',
    authDomain: 'weblearn-9f82a.firebaseapp.com',
    storageBucket: 'weblearn-9f82a.firebasestorage.app',
    measurementId: 'G-BB35K0QTV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTdtM6kEU0-QPixin8I6QsNAr7YKjUAN8',
    appId: '1:336645454105:android:ebadfcbf1fd2f6a6b3ed88',
    messagingSenderId: '336645454105',
    projectId: 'weblearn-9f82a',
    storageBucket: 'weblearn-9f82a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyJTxGc0POmoQLZHpWZC9VFBdNvZ99Q_c',
    appId: '1:336645454105:ios:eeed9ca91e25abf2b3ed88',
    messagingSenderId: '336645454105',
    projectId: 'weblearn-9f82a',
    storageBucket: 'weblearn-9f82a.firebasestorage.app',
    iosBundleId: 'com.example.weblearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyJTxGc0POmoQLZHpWZC9VFBdNvZ99Q_c',
    appId: '1:336645454105:ios:eeed9ca91e25abf2b3ed88',
    messagingSenderId: '336645454105',
    projectId: 'weblearn-9f82a',
    storageBucket: 'weblearn-9f82a.firebasestorage.app',
    iosBundleId: 'com.example.weblearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEZCtlmIamTGlZkWU_vuoBEePyqKhMOHM',
    appId: '1:336645454105:web:ad9a4bdf87de5135b3ed88',
    messagingSenderId: '336645454105',
    projectId: 'weblearn-9f82a',
    authDomain: 'weblearn-9f82a.firebaseapp.com',
    storageBucket: 'weblearn-9f82a.firebasestorage.app',
    measurementId: 'G-N4TYB1NF1X',
  );
}
